name: LegacyCraft
main: com.pwnion.legacycraft.LegacyCraft
version: 1.0
api-version: 1.14
depend: [Citizens]
softdepend: [Citizens]
commands:
    legacycraft:
        aliases: [lc]
    test:
        usage: /<command>