package com.pwnion.legacycraft.abilities.inventory;

//All inventory names
public enum InvName {
	CHARACTER_BUILD_MENU,
	WEAPON_ENHANCEMENTS,
	SELECT_A_CLASS,
	SELECT_AN_ASPECT,
	IGNIS_STRIKER,
	TERRA_STRIKER,
	VACUOUS_STRIKER,
	ARCTIC_STRIKER,
	IGNIS_VANGUARD,
	TERRA_VANGUARD,
	VACUOUS_VANGUARD,
	ARCTIC_VANGUARD,
	IGNIS_ROGUE,
	TERRA_ROGUE,
	VACUOUS_ROGUE,
	ARCTIC_ROGUE,
	IGNIS_SHAMAN,
	TERRA_SHAMAN,
	VACUOUS_SHAMAN,
	ARCTIC_SHAMAN,
}
