package com.pwnion.legacycraft.abilities.inventory;

//All inventory names
public enum InvName {
	CHARACTER_BUILD_MENU,
	WEAPON_ENHANCEMENTS,
	SELECT_A_CLASS,
	SELECT_AN_ASPECT,
	IGNIS_STRIKER,
	TERRA_STRIKER,
	AER_STRIKER,
	AQUA_STRIKER,
	IGNIS_VANGUARD,
	TERRA_VANGUARD,
	AER_VANGUARD,
	AQUA_VANGUARD,
	IGNIS_ROGUE,
	TERRA_ROGUE,
	AER_ROGUE,
	AQUA_ROGUE,
	IGNIS_SHAMAN,
	TERRA_SHAMAN,
	AER_SHAMAN,
	AQUA_SHAMAN
}
